### ISSUE TITLE
Add more information to path descriptions in the OpenAPI definition document

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-processes#147]
Suggestion 1

```yaml
  /:
    get:
      tags:
      - Capabilities
      summary: landing page of this API
      description: >
         The landing page provides links to the:
           * The APIDefinition (no fixed path),
           * The Conformance statements (path /conformance),
           * The processes metadata (path /processes).doss
           * the execute endpoint (path /jobs).

         For more information, see [Section 7.2](http://docs.ogc.org/DRAFTS/18-062.html#sc_landing_page).

```

Suggestion 2

```yaml

  /conformance:
    get:
      tags:
      - Conformance
      summary: information about standards that this API conforms to
      description: |
         A list of all conformance classes, specified in a standard, that the server conforms to.

         | Conformance class | URI |
         |-----------|-------|
         |Core|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/core|
         |OGC Process Description|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/ogc-process-description|
         |JSON|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/json|
         |HTML|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/html|
         |OpenAPI Specification 3.0|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/oas30|
         |Job list|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/job-list|
         |Callback|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/callback|
         |Dismiss|http://www.opengis.net/spec/ogcapi-processes-1/1.0/conf/dismiss|

         For more information, see [Section 7.4](http://docs.ogc.org/DRAFTS/18-062.html#sc_conformance_classes).
```

Suggestion 3

```yaml

  /processes:
    get:
      tags:
      - Processes
      summary: retrieve available processes
      description: |
         The list of processes contains a summary of each process the OGC API - Processes offers, including the link to a more detailed description of the process.

         For more information, see [Section 7.7](http://docs.ogc.org/DRAFTS/18-062.html#sc_process_list).
```

Suggestion 4

```yaml

  /processes/{id}:
    get:
      tags:
      - ProcessDescription
      summary: retrieve a process description
      description: |
         The process description contains information about inputs and outputs and a link to the execution-endpoint for the process. The Core does not mandate the use of a specific process description to specify the interface of a process. That said, the Core requirements class makes the following recommendation:

         Implementations SHOULD consider supporting the OGC process description.

         For more information, see [Section 7.8](http://docs.ogc.org/DRAFTS/18-062.html#sc_process_description).
```
