### ISSUE TITLE
Correction to execute.yaml & input.yaml defining inputs

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-processes#152]
The following changes correct the execute request OpenAPI schema so as not to allow an infinite nesting of input dictionaries.
The key -> input or list of inputs dictionary should only be at the execute.yaml level.

[***execute.yaml:***](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/execute.yaml)
```yaml
inputs:
   additionalProperties:
      oneOf:
      - $ref: "input.yaml"
      - type: array
         items:
            - $ref: "input.yaml"
```

[***input.yaml:***](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/openapi/schemas/input.yaml)
```yaml
oneOf:
  - $ref: "inlineOrRefData.yaml"
  - $ref: "boundingBoxData.yaml" 
```
