### ISSUE TITLE
Spacing yaml indentation issue in schema definition for ogcapppkg

### ISSUE THREAD

**Issue by gardengeek99** [opengeospatial/ogcapi-processes#153]
I think there is an issue with
https://github.com/opengeospatial/ogcapi-processes/blob/master/extensions/transactions/openapi/schemas/ogcapppkg.yaml
```
  executionUnit:
    type: array
      minItems: 1
      items:
        type: object
        example:
          type: docker
          image: mydocker/ndvi:latest

```
should be
```
  executionUnit:
    type: array
    minItems: 1
    items:
      type: object
      example:
        type: docker
        image: mydocker/ndvi:latest

```
