### ISSUE TITLE
The boundingBoxData.json file is missing but required by the new example 

### ISSUE THREAD

**Issue by gfenoy** [opengeospatial/ogcapi-processes#163]
In the [new example of an echo service description](https://github.com/opengeospatial/ogcapi-processes/blob/master/core/examples/json/ProcessDescription.json) there is a reference to a boundingBoxData.json file defining a schema for the BoundingBox data. Unfortunately, the file is not present in the repo.

**Comment by pvretano** [comment]
Oops ... forgot to remove that.  @gfenoy I'll fix it directly in the master branch.

**Comment by gfenoy** [comment]
I would like to ensure that our implementation is producing the proper schema for BoundingBox data type (which was available in previous WPS standard versions). Can you please tell me if the following schema embedded in input definition is correct:

````
    "c": {
      "title": "BoundingBox Input ",
      "description": "A boundingbox input ",
      "schema": {
        "type": "object",
        "required": [
          "bbox",
          "crs"
        ],
        "properties": {
          "bbox": {
            "type": "array",
            "minItems": 4,
            "maxItems": 6,
            "items": {
              "type": "number",
              "format": "double"
            }
          },
          "crs": {
            "type": "string",
            "default": "urn:ogc:def:crs:EPSG:6.6:4326",
            "enum": [
              "urn:ogc:def:crs:EPSG:6.6:4326",
              "urn:ogc:def:crs:EPSG:6.6:3785"
            ]
          }
        }
      }
    }
````

**Comment by pvretano** [comment]
@gfenoy the schema that I use is:
```
type: object
required:
  - bbox
properties:
  bbox:
    type: array
    minItems: 4
    maxItems: 6
    items:
      type: number
  crs:
    type: string
    format: uri
    default: "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
    enum:
      - "http://www.opengis.net/def/crs/OGC/1.3/CRS84"
      - "http://www.opengis.net/def/crs/OGC/0/CRS84h"
```
But now that you ask I think I forgot something in the `openapi/schemas` directory.  I was supposed to add a `bbox.yaml` file with the schema of a **standard** bbox that everyone can reference.   That way, in your process definition, you can say:

```
   c:
     $ref: ../../openapi/schema/bbox.yaml
```
and that way everyone uses the same bbox.  I will add bbox.yaml to the openapi/schemas directory now.

**Comment by pvretano** [comment]
@gfenoy done!  I added bbox.yaml so you can reference that if you like.

**Comment by cportele** [comment]
In Features we have changed (in the Editor's draft)

```yaml
minItems: 4
maxItems: 6
```

to 

```yaml
oneOf:
- minItems: 4
  maxItems: 4
- minItems: 6
  maxItems: 6
```

to be more precise.
