### ISSUE TITLE
Ambiguity around array inputs?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-processes#373]
If I want to provide an array of max. two strings, how am I supposed to do that?

1) Purely JSON Schema:
```yaml
inputs:
  example:
    schema:
      type: array
      maxItems: 2
      items:
        type: string
```

2) maxOccurs:
```yaml
inputs:
  example:
    maxOccurs: 2
    schema:
      type: string
```

Is it equivalent?

3) And what does the following mean? 
```yaml
inputs:
  example:
    maxOccurs: 2
    schema:
      type: array
      maxItems: 2
      items:
        type: string
```

(Provided in YAML for simplicity)

**Comment by gfenoy** [comment]
> Is it equivalent?

I think they are, yes.

> 
> And what does the following mean?
> 
> ```
> inputs:
>   example:
>     maxOccurs: 2
>     schema:
>       type: array
>       maxItems: 2
>       items:
>         type: string
> ```

IMO, it means that your process is expecting at least one array with maximum 2 string items and support also, for this input, 2 arrays of maximum 2 string.

**Comment by pvretano** [comment]
No they are not equivalent ... using @m-mohr example...

The first schema can result in an input like this:
````
example: [ "value1","value2" ]
````
The second schema can result in an input like this:
````
example:[["value1","value2"],["value3"]]
````

The "schema" object defines the schema of a **single** instance of an input value.  If the single instance happens to be an array then so be it.  The `minOccurs` and `maxOccurs` indicate the cardinality on the input.  

Both the input and output need more explanation and I have it on my todo list to update the specification which I am hoping to do before the code sprint.

**Comment by m-mohr** [comment]
@pvretano How can the second schema (I just added numbers above, to be very explicit here) lead to an array of arrays? The schema is `type: string` only.

**Comment by pvretano** [comment]
@m-mohr as I said, the `schema` member defines the schema of a single instance of the input.  In this case a `string`.  However, the number of time that input can appear in an execute request is controlled by `minOccurs` and `maxOccurs` and the convention is that mulitple values for an input are encoded in JSON using an array.

**Comment by m-mohr** [comment]
Sorry, but I don't get it:

How can the following schema:
```
inputs:
  example:
    maxOccurs: 2
    schema:
      type: string
```

allow the following input?

```
example:[["value1","value2"],["value3"]]
```

Where does the inner array come from? I really don't understand it.

**Comment by pvretano** [comment]
@m-mohr sorry I may have gotten the schema numbers mixed up ... let me try again. 

This schema ...
````
inputs:
  example:
    schema:
      type: array
      maxItems: 2
      items:
        type: string
````
leads to inputs like this:
````
example: ["value1","value2"]
````

This schema ...
````
inputs:
  example:
    maxOccurs: 2
    schema:
      type: string
````
leads to inputs like this:
````
example: ["value1","value2"]
````
So these two are equivalent.

But this schema:
````
inputs:
  example:
    maxOccurs: 2
    schema:
      type: array
      maxItems: 2
      items:
        type: string
````
leads to inputs like this:
````
example: [["value1","value2"],["value3"]]
````

Does this help?

**Comment by m-mohr** [comment]
Yes, this is what I expected, thanks. 

I'm not sure why do deviated from JSON Schema and added min/maxOccurs instead of just using the min/maxItems, but if I can just translate from min/maxOccurs to minItems/maxItems with an array type wrapper in JSON Schema, I guess it works for me.

**Comment by gfenoy** [comment]
For this schema: 

> ```
> inputs:
>   example:
>     schema:
>       type: array
>       minItems: 1
>       maxItems: 2
>       items:
>         type: string
> ```

There is still something missing, in case the example input takes only one value, it is not passed as an array.

So we should add a `oneOf` to add this option too, we then use the same type as the one for the item within the array. 

To be complete, we also need to add the json object that can be used to pass a reference for an input.

**Comment by pvretano** [comment]
@gfenoy I could be wrong but I don't think that is correct.  Then single instance of the input is defined as an array so it will always be an array.  If you specify 1 value that you still need to use an array...
````
example: ["value2"]
````

This is why I need to update the specification to clarify all this ... we have the schema in the specification but very little discussion about what they imply in relation to encoding an execute request.

I hope the others, @jerstlouis @fmigneault, etc. chime in so we can get concensus about this before I start writing.  This issue is also related to the email that I sent to @gfenoy and other about this question.  Similar issues arrise with the outputs too.  I'm working on a PR to try an clarify all of this in the specification that should be ready soon.

**Comment by m-mohr** [comment]
Why not just ditch min/maxOccurs and purely rely on JSON Schema?

**Comment by pvretano** [comment]
@m-mohr not opposed to that but lets see what the others say.

**Comment by gfenoy** [comment]
@pvretano I would be in favour of this move personally.

Are these comments https://github.com/opengeospatial/ogcapi-processes/issues/168#issuecomment-822437574, https://github.com/opengeospatial/ogcapi-routes/issues/17#issuecomment-819714011 related?

**Comment by fmigneault** [comment]
I would love to have this explicitly detailed in the specification. 

Because there was a lot of confusion in the past (as this thread shows) regarding input cardinality vs "single value array", CRIM's implementation evolved into trying to auto-detect `minOccurs`/`maxOccurs` and patch the corresponding representation in `schema` with `minItems`/`maxItems` and vice-versa. If an input specified `minOccurs: 1`/`maxOccurs: 2`, we would extend the `schema` with a `oneOf` such that it supports `"value1"`, `["value1"]` and `["value1", "value2"]`. 

Using exclusively `schema` could be a good move to remove this confusion, but to remain backward compatible, processes would need to adjust their schemas without `minOccurs: 1`/`maxOccurs: 1` to: 
```yaml
schema:
  oneOf:
    - <original-schema>
    - type: array
      items: <original-schema>
      minItems: 1
      maxItems: 1
```
And processes using `minOccurs: 2` to the following to replicate what cardinality provided for a "single value array" : 
```yaml
schema:
  type: array
  items: <original-schema>
  minItems: 2
```

We need to consider very carefully how to handle cases of multiple nested arrays, so there is no ambiguity in process descriptions whether the I/O represent many single values or a single array value.

**Comment by pvretano** [comment]
@fmigneault its on my todo list ... both the inputs and output are under-described!

**Comment by jerstlouis** [comment]
>  I am not sure getting rid of minOccurs/maxOccurs at this time would be the right move as it would introduce quite a bit of disruption.

This is why I am suggesting to simply _deprecate_ it, as in discourage implementors to deploy new proceses that relies on minOccurs / maxOccurs (so they default to 1), and using instead `type: array` with `maxItems:`.

**Comment by pvretano** [comment]
Actually, I don't think we can get rid of `minOccurs`/`maxOccurs` without moving wholesale to using JSON Scheme to define the inputs.  Consider this input definition:
````
"inputs" : {
  "myInput": {
    "minOccurs": 0,
    "maxOccurs": 1,
    "schema": {
      "type": "string"
    }
  },
  .
  .
  .   
}
````
If we get rid of `minOccurs` and `maxOccurs` then how do we indicate that `myInput` is optional?   The only thing I can think of is to go all in on JSON Schema and say that the value of "inputs" is an object defined using  JSON-Schema that specifies all the inputs the process takes.  That is ...
````
"inputs": {
  "type": "object",
  "required": ["myOtherInput"],
  "properties": {
    "myInput": {
      "type": "string"
    },
    "myOtherInput": {
      "type": "number"
    },
    .
    .
    .
}
````
Such a change is a breaking change and so we would have to go to V2.0. ... I think.  Comments?

**Comment by m-mohr** [comment]
@pvretano Having a default value could indicate that a parameter is optional.

```json
"inputs" : {
  "myInput": {
    "schema": {
      "type": ["string", "null"],
      "default": null
    }
  }, ...
}
```

**Comment by jerstlouis** [comment]
@pvretano @m-mohr I think we could simply deprecate `maxOccurs`, and any value except `minOccurs: 0` and the default `1`.

**Comment by fmigneault** [comment]
If `minOccurs` needs to be preserved, then I would prefer to keep `maxOccurs` as well. Otherwise, we would have weird combinations of `minOccurs` out of `schema` and `maxItems` in the `schema`. The `default: null` proposal makes sense in my opinion if both are removed.

In order to reduce the ambiguity between array as a cardinality specifier and the JSON array container passed as a single value, we could disallow this kind of input for `maxOccurs: 1`:
```yaml
inputs:
  input_single_value_array: [1,2,3]
``` 
Instead, a single-value JSON array would have to be explicitly nested under `value` just like it must be done in the case for JSON complex objects to remove the ambiguity with cardinality. 
```yaml
inputs:
  input_single_value_array: 
    value: [1,2,3]
``` 
And with this, the only case where an array could be directly provided under the input/output ID would be to represent cardinality. The following would always be equivalent and would assume `maxOccurs>1`:
```yaml
inputs:
  input_min_occurs2_short_form: [1, 2, 3]
  input_min_occurs2_long_form:
    - value: 1
    - value: 2
    - value: 3
``` 
In the above example, each `int` can be replaced individually by anything, including a `href` or a complex JSON (including a nested array), without changing the interpretation of the first level array as the cardinality, contrary to the current definition that could mix the short form to be a "single value" that just so happens to be a JSON array.
