### ISSUE TITLE
How can I extend a response schema?

### ISSUE THREAD

**Issue by mcucchi9** [opengeospatial/ogcapi-processes#376]
Hi,

I'm developing an API based upon the OGC API - Processes standard, using the Python framework FastAPI.
I would like to extend the schema of the `GET /jobs/{job_id}` endpoint's response so that it returns predefined additional fields, and I would also like those additional fields to be shown in the OpenAPI documentation.
Stated in other words, I would like my API to have a response schema for the cited endpoint which is an extension of the schema defined in the OGC API - Processes.

I read in the [OGC API - Processes - Part1: Core](https://docs.ogc.org/is/18-062r2/18-062r2.html) document, Par. 7.2.2, Note 1:

> The term “…​based upon the OpenAPI 3.0 schema…​” used in the requirements of this specification means that OpenAPI 3.0 is used to define:
> 
>  all the required properties of the respective request/response schema,
>  and any optional properties of the respective request/response schema.
> **It also means that unless explicitly excluded these schemas are extensible with additional properties not defined in the schema** using the [additionalProperties](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md#schemaObject) mechanism defined in the [OpenAPI 3.0 specification](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.0.md).

From this I assume that, since the `GET /jobs/{job_id}` endpoint's response schema ([statusInfo.yaml](https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml)) does not explicitly exclude it, I can extend it with additional properties.

Anyway, it is not entirely clear to me how should I use the "additionalProperties" mechanism in this context.

Thanks in advance.

**Comment by pvretano** [comment]
@mcucchi9 yes, you can additional members to the statusInfo.yaml schema.  Compliant OGC API Processes clients will simply ignore the additional fields.  You can also add them to the OpenAPI document too ... but again you have to be aware that complaint clients may not recognize your extensions.

**Comment by mcucchi9** [comment]
Ok, so I can simply define my statusInfo.yaml with an additional `myAdditionalField` field as follow:

```
type: object
required:
   - jobID
   - status
   - type
properties:
   processID:
      type: string
   type:
      type: string
      enum:
        - process
   jobID:
      type: string
   status:
      $ref: "statusCode.yaml"
   message:
      type: string
   created:
      type: string
      format: date-time
   started:
      type: string
      format: date-time
   finished:
      type: string
      format: date-time
   updated:
      type: string
      format: date-time
   progress:
      type: integer
      minimum: 0
      maximum: 100
   links:
      type: array
      items:
         $ref: "link.yaml"
   myAdditionalField:
      type: string
```

is that correct?

**Comment by pvretano** [comment]
@mcucchi9 yup ...

**Comment by mcucchi9** [comment]
Perfect, thanks!

**Comment by fmigneault** [comment]
If you want to keep the distinction explicit between wihch fields are from OGC API - Processes and the ones provided by your implementation, you can define the schema this way:

```yaml
allOf: 
  - $ref: https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/schemas/statusInfo.yaml
  - type: object
    properties:
      ... # anything you want here
```
