### ISSUE TITLE
Metadata schemas should allow in-line process metadata.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#389]
Right now, according to the schema in [metadata.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-core/metadata.yaml) a process can only reference metadata about the process. 

It would be nice if (a) the reference mechanism just used the [standard link schema](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/common-core/link.yaml) and (b) allowed the metadata to be encoded in-line to make it easier to harvest by a catalog (for example).

A revised schema might look like this:

````
oneOf:
  - type: object
  - $ref: ../common/link.yaml
````
... or, it we want to preserve backward compatability, it could look like this

````
oneOf:
  - type: object
    properties:
       title:
          type: string
       role:
          type: string
       href:
          type: string
  - type: object
    properties:
       title:
          type: string
       role:
          type: string
       value:
          type: object
````

I'm open to other suggestions ...

**Comment by fmigneault** [comment]
I support this proposal. CRIM's implementation already supports this unofficially. 
The specific definitions we employ is as follows (aka `oneOf` [metadata.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-core/metadata.yaml?rgh-link-date=2024-01-11T01%3A46%3A28Z) and [link.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/common-core/link.yaml?rgh-link-date=2024-01-11T01%3A46%3A28Z) but with added `role`) : 
![image](https://github.com/opengeospatial/ogcapi-processes/assets/19194484/2c3e01cb-6db9-41a0-a66f-f415ee8498d8)

**Comment by pvretano** [comment]
@fmigneault looks good ... the only difference from what I am doing is that `value`, in my implementation, is an `object` rather than a string so that I can embed structred metadata.  

How does this schema for metadata.yaml look to you? 

````
oneOf:
  - allOf:
    - $ref: ../common-core/link.yaml
    - type: object
      properties:
        role:
          type: string
  - type: object
    properties:
       role:
          type: string
       title:
          type: string
       lang:
          type: string
       value:
         oneOf:
           - type: string
           - type: object
````
