### ISSUE TITLE
Exception message in status info ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-processes#392]
Right now the [statusInfo.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-core/statusInfo.yaml) schema has a `message` key that is of type `string`.  

I think `message` key should either be a `string` OR an `object` and specifically, if the job has failed, the `message` should be an [exception.yaml](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/common-core/exception.yaml) object which conforms to [RFC7807](https://datatracker.ietf.org/doc/html/rfc7807).

This would require that the definition of the `message` key be:
````
message:
  oneOf:
    - type:string
    - $ref: "../common-core/exception.yaml"
````
