### ISSUE TITLE
Explicit schema references for listing of qualified value or links as inputs/outputs items

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-processes#416]
Using this definition: 
https://github.com/opengeospatial/ogcapi-processes/blob/5066e04d4313257b72f1d1c230775c570e5cf1af/openapi/schemas/processes-core/inlineOrRefData.yaml#L1-L4

It is possible to define the following:
```yaml
outputs:
  inline_value_output: "abc"
  inline_array_output: [1, 2, 3]
  qualified_json_output:
    mediaType: application/json
    value: {"xyz": 123}
  link_output:
    type: application/json
    href: "https://host.com/some.json"
```

But there is no explicit reference for this kind of structure: 
```yaml
outputs:
  qualified_array_output:
    - mediaType: text/plain
      value: xyz
    - mediaType: application/json
      value: {"abc": 123}
    - type: application/json
      href: "https://host.com/some.json"
```

Because [`inputValueNoObject`](https://github.com/opengeospatial/ogcapi-processes/blob/master/openapi/schemas/processes-core/inputValueNoObject.yaml) explicitly omits the `object` type to ensure it is instead embedded within a (qualified) `value`, that more context (i.e.: with `mediaType`, `schema`, etc.) can be provided, and to avoid ambiguous nested-objects schemas, there seems to be an implicit hint that an array of objects/links could also be defined.

While the above qualified value/link array will "work" because of the following schema, the intention is not as clear as for the case of non-array value outputs.
https://github.com/opengeospatial/ogcapi-processes/blob/5066e04d4313257b72f1d1c230775c570e5cf1af/openapi/schemas/processes-core/inputValueNoObject.yaml#L6-L7

The lack of something more concrete than the "anything" (i.e.: `{}`) does not help implementers know whether an array of qualified inputs/outputs is a valid construct or not, or rather, whether clients should be able to handle these cases.
