### ISSUE TITLE
Small bug: a default cannot be an array

### ISSUE THREAD

**Issue by edwinvandenbelt** [opengeospatial/ogcapi-processes#504]
The TransmissionMode.yaml contains this:

```yaml
type: string
enum:
  - value
  - reference
default:
  - value
```

The default value should be a single value, not an array.

```yaml
type: string
enum:
  - value
  - reference
default: value
```
