### ISSUE TITLE
Question: how to overcome the limitation of the 'Link' object

### ISSUE THREAD

**Issue by edwinvandenbelt** [opengeospatial/ogcapi-processes#505]
The link object uses web linking, but does not take other HTTP methods into account. Can it be extended one way or the other, or is there a standard for this?

I need something like this:
```json

"links": [
              {
                "rel": "open",
                "href": "https://some-url.com/api/v1/processes/open-case/execute",
                "type": "application/json",
                "method": "POST",
                "description": "call this URL to open the case",
                "body": { "id": "case4392" },
                "headers": {
                  "Authentication": "Bearer [JWT-token]"
                }
              }
            ]
```

In practice, can it be extended with properties like 'method', 'body' and headers? The receiving party can immediately execute the link, instead of just performing a GET (the default Link). Working this way, you can also provide chains of process steps, fully controlled by the client.

```yaml

type: object
required:
  - href
properties:
  href:
    type: string
  rel:
    type: string
    example: service
  type:
    type: string
    example: application/json
  hreflang:
    type: string
    example: en
  title:
    type: string
  method:
    type: string
    description: to indicate the http method.
    enum: [ POST, GET, DELETE, PATCH ]
  body:
    type: object
    description: the (prefilled) body for the request
  headers:
    type: object
    additionalProperties:
      type: string
```
