### ISSUE TITLE
Question: why it is needed to have an 'inputs' and 'outputs'?

### ISSUE THREAD

**Issue by edwinvandenbelt** [opengeospatial/ogcapi-processes#506]
In the core part, there is the GET /api, returning the complete API in OpenAPI. When you look at a GET /processes/{processId}, you're more or less confronted with the same information, except it is now in (a kind of) JSONSchema. This provides a basis for misinterpretations and discrepancies. Why is a simple reference to the /api not enough? 

__inputDescription.yaml__
```yaml 

allOf:
  - $ref: "descriptionType.yaml"
  - type: object
    required:
      - schema
    properties:
      minOccurs:
        type: integer
        default: 1
      maxOccurs:
        oneOf:
          - type: integer
            default: 1
          - type: string
            enum:
              - "unbounded"
      schema:
        $ref: "schema.yaml"
```

```yaml 

allOf:
  - $ref: "descriptionType.yaml"
  - type: object
    required:
      - schema
    properties:
      minOccurs:
        type: integer
        default: 1
      maxOccurs:
        oneOf:
          - type: integer
            default: 1
          - type: string
            enum:
              - "unbounded"
      definition:
        $ref: "reference.yaml"
        example: '#/components/schemas/some_object'
```

And this applies to outputDescription.yaml as well. It would also mean that the complete 'schema.yaml' and everything within it, are not needed anymore (questionmark).
